### ISSUE TITLE
Teacher Review #4

### ISSUE THREAD

**Issue by ashwinbabu888** [ashwinbabu888/chicken-mcnuggets#37]

**Comment by jm1021** [comment]
Discussed tickets, need more direct assignments.   Suggesting research requirement be added to comments to ticket.   We need to establish plan to get people who are not working on track, even make a ticket for them to go to tutorial.  .75

**Comment by jm1021** [comment]
Time box for readme is a big need.  Perhaps TOC at top of README to relevant information for the week.  Overview was good, but I don't see much talk about any of the labs or integration.  Attention to details is missing, you are leaving it to me to do all correlation.  I don't see any self grade.  1.25

**Comment by jm1021** [comment]
Individual work.  I only see Ashwin with an backend code.  Caleb and Varnit have done some HTML code, but nothing that I saw looks adventurous for two weeks of prototyping.

Ashwin 1.75
Caleb 1.25
Varnit 1.25
Yeionjoon 0

**Comment by jm1021** [comment]
Journals and AP.
Ashwin have nice CB journal.  I do not see any notes form TPT or TT sessions.  4.75 / 5.0
Varnit and Yeonjoon journal is locked to my access.  Varnit did CB work 2.5/50, Yeonjoon did not do CB work 0/5.0
