### ISSUE TITLE
Week 8 Review Ticket

### ISSUE THREAD

**Issue by calebkimsd** [ashwinbabu888/chicken-mcnuggets#71]
Caleb, Yeonjoon, Varnit, Ashwin - Chicken-McNuggets

https://github.com/ashwinbabu888/chicken-mcnuggets/blob/master/README.md#week-7-8-issues--progress--grading
(READ.ME with a complete breakdown of grading with artifacts and links to code and evidence. ^^)

Presentations: 4.5/5
ASCII art lab: 3/3 (indicated by student graders on 10/19)
Unit 8: 2/2

Varnit: 9 (makeup with presentation)
Ashwin: 8.5 (makeup with presentation)
Caleb: 9.5
Yeonjoon: 9.5

We still have many improvements to make in the future with our knowledge and DNU website. We will work harder so we can finish our website and reflect our learning throughout the trimester.

**Comment by RohanKoshy** [comment]
The potential is there. I like how you are attempting to add several games to the frontend.

**Comment by paul-bokelman** [comment]
good job
